name: Steph Hinds
favicon: null
layout_spectrum: 0.596399963600561
typography_spectrum: 0.17823
title: 'Sharing the highs, lows & tips from Growthwise'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2d8d6'
    - '#ffffff'
    - '#030000'
    - '#4e4f51'
    - '#be8864'
  brandStrength: 0.5
  lightness: 0.12276680767536163
  saturation: 0.16031200997531414
  rhythmicContrast: 0.35763080045580864
purpose: []
