name: Steph Hinds
favicon: null
layout_spectrum: 0.49858
typography_spectrum: 0.50193
title: 'Sharing the highs, lows & tips from Growthwise'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2d8d6'
    - '#ffffff'
    - '#030000'
    - '#4e4f51'
    - '#be8864'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
